Makefile: Drop armv8-a target ARM architecture for clang
error: unknown target CPU 'armv8-a+crc+crypto'

Clang doesn't support 'armv8-a';while GCC do.

Signed-off-by: GeoPD <geoemmanuelpd2001@gmail.com>